// Production build: bundle the app (injecting the version + git hash via Bun's
// `define`), then emit the PWA files (manifest, icons, network-first service
// worker) into dist/ with STABLE names and wire their <link>s into the built
// HTML. We write the PWA files ourselves (rather than letting Bun bundle them)
// so their names stay stable — the service worker must live at a fixed URL, and
// the manifest must reference the icons by a predictable path.
import pkg from '../package.json';
import { rm, cp, writeFile, readFile } from 'node:fs/promises';

const root = new URL('..', import.meta.url).pathname;
const hash = (await Bun.$`git rev-parse --short HEAD`.text().catch(() => '')).trim() || 'unknown';
const version = pkg.version;
const themeColor = '#5b8fd0';

await rm(`${root}dist`, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [`${root}index.html`],
  outdir: `${root}dist`,
  minify: true,
  sourcemap: 'linked',
  publicPath: './',
  define: { __APP_VERSION__: JSON.stringify(version), __GIT_HASH__: JSON.stringify(hash) },
});
if (!result.success) { console.error(result.logs.join('\n')); process.exit(1); }

// PWA icons (pre-generated from assets/logo.png, tracked in the repo).
await cp(`${root}assets/icon-192.png`, `${root}dist/icon-192.png`);
await cp(`${root}assets/icon-512.png`, `${root}dist/icon-512.png`);
await cp(`${root}assets/icon-maskable-512.png`, `${root}dist/icon-maskable-512.png`);

// Web app manifest. Relative start_url/scope so it works under the GitHub Pages
// project subpath (https://<user>.github.io/ogn-3d-viewer/).
const manifest = {
  name: 'OGN 3D Viewer',
  short_name: 'OGN 3D',
  description: pkg.description,
  start_url: './',
  scope: './',
  display: 'standalone',
  background_color: '#0c1015',
  theme_color: themeColor,
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
await writeFile(`${root}dist/manifest.json`, JSON.stringify(manifest, null, 2));

// Network-first service worker. The cache name is busted by the git hash, so a
// new deploy installs a fresh worker that purges old caches and takes control
// immediately — the app updates as soon as the user is online. Only same-origin
// GET requests are handled; cross-origin (OGN API, map tiles) go to the network
// untouched. Offline, we fall back to the cache.
const sw = `// Auto-generated by scripts/build.ts — do not edit.
const CACHE = 'ogn-3d-${hash}';
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil((async () => {
  const keys = await caches.keys();
  await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
  await self.clients.claim();
})()));
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return; // leave API/tiles to the network
  e.respondWith((async () => {
    try {
      const res = await fetch(req);
      if (res && res.ok) { const c = await caches.open(CACHE); c.put(req, res.clone()); }
      return res;
    } catch (err) {
      const cached = await caches.match(req);
      if (cached) return cached;
      throw err;
    }
  })());
});
`;
await writeFile(`${root}dist/sw.js`, sw);

// Wire the manifest + theme/icon links into the built HTML (stable names, so
// Bun never rewrites or hashes them).
const htmlPath = `${root}dist/index.html`;
let html = await readFile(htmlPath, 'utf8');
html = html.replace('</head>',
  `<link rel="manifest" href="manifest.json">` +
  `<meta name="theme-color" content="${themeColor}">` +
  `<link rel="apple-touch-icon" href="icon-192.png"></head>`);
await writeFile(htmlPath, html);

console.log(`built ogn-3d-viewer ${version} (${hash}) + PWA (manifest, icons, sw.js)`);
