// Production build: bundle the app (injecting the version + git hash via Bun's
// `define`), then emit the PWA files (manifest, icons, service worker) into
// dist/ with STABLE names and wire their <link>s into the built HTML. We write
// the PWA files ourselves (rather than letting Bun bundle them) so their names
// stay stable — the service worker must live at a fixed URL, and the manifest
// must reference the icons by a predictable path.
import pkg from '../package.json';
import { rm, cp, writeFile, readFile } from 'node:fs/promises';

const root = new URL('..', import.meta.url).pathname;
const hash = (await Bun.$`git rev-parse --short HEAD`.text().catch(() => '')).trim() || 'unknown';
const version = pkg.version;
const themeColor = '#5b8fd0';

await rm(`${root}dist`, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [`${root}index.html`],
  outdir: `${root}dist`,
  minify: true,
  sourcemap: 'linked',
  publicPath: './',
  define: { __APP_VERSION__: JSON.stringify(version), __GIT_HASH__: JSON.stringify(hash) },
});
if (!result.success) { console.error(result.logs.join('\n')); process.exit(1); }

// PWA icons (pre-generated from assets/logo.png, tracked in the repo).
await cp(`${root}assets/icon-192.png`, `${root}dist/icon-192.png`);
await cp(`${root}assets/icon-512.png`, `${root}dist/icon-512.png`);
await cp(`${root}assets/icon-maskable-512.png`, `${root}dist/icon-maskable-512.png`);

// PWA install screenshots (downscaled ~1280px copies of the README captures),
// for the richer install dialog on desktop Chrome/Edge.
const SHOTS: [string, string, string][] = [
  ['overview', '1280x665', 'Overview map with flight tracks'],
  ['cockpit', '1280x663', 'Cockpit (first-person) view'],
  ['chase', '1280x662', 'Chase camera view'],
  ['graphs', '1280x655', 'Flight data graphs'],
];
for (const [name] of SHOTS) await cp(`${root}assets/screencaptures/pwa-${name}.png`, `${root}dist/ss-${name}.png`);

// Web app manifest. Relative start_url/scope so it works under the GitHub Pages
// project subpath (https://<user>.github.io/ogn-3d-viewer/).
const manifest = {
  id: './',                 // stable app identity (avoids Chrome's "no id" warning)
  name: 'OGN 3D Viewer',
  short_name: 'OGN 3D',
  description: pkg.description,
  lang: 'en',
  dir: 'ltr',
  start_url: './',
  scope: './',
  display: 'standalone',
  orientation: 'any',
  categories: ['sports', 'travel', 'utilities'],
  background_color: '#0c1015',
  theme_color: themeColor,
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
  screenshots: SHOTS.map(([name, sizes, label]) => ({
    src: `ss-${name}.png`, sizes, type: 'image/png', form_factor: 'wide', label,
  })),
};
await writeFile(`${root}dist/manifest.json`, JSON.stringify(manifest, null, 2));

// Service worker with two strategies:
//  • App shell (same-origin): NETWORK-FIRST in a hash-busted cache, so a new
//    deploy installs a fresh worker that purges old shells and updates the app
//    as soon as the user is online; offline falls back to cache.
//  • Map tiles (Terrarium DEM on S3, Esri imagery): CACHE-FIRST in a persistent
//    cache that survives deploys, so revisits are instant and tiles are never
//    re-downloaded. Bounded (oldest trimmed) to keep storage in check. Both
//    providers send CORS headers (deck loads them with crossOrigin), so the
//    responses are cacheable normally.
//  • Everything else cross-origin (OGN API): untouched, straight to network.
const sw = `// Auto-generated by scripts/build.ts — do not edit.
const CACHE = 'ogn-3d-${hash}';
const TILES = 'ogn-tiles-v1';
// Persistent tile cache size scales with device RAM (~30 KB/tile on disk):
// phones (deviceMemory ≤4, or undefined on Safari) keep ~800 tiles (~25 MB),
// desktops (≥8) keep ~4000 (~120 MB). The browser also evicts the whole cache
// on its own under storage pressure, so this is a soft ceiling.
const TILE_MAX = (navigator.deviceMemory || 4) >= 8 ? 4000 : 800;
const isTile = (u) => u.href.includes('elevation-tiles-prod') || u.hostname.endsWith('arcgisonline.com');
async function trim() {
  const c = await caches.open(TILES), keys = await c.keys();
  for (let i = 0; i < keys.length - TILE_MAX; i++) await c.delete(keys[i]);
}
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (e) => e.waitUntil((async () => {
  const keys = await caches.keys();
  await Promise.all(keys.filter((k) => k !== CACHE && k !== TILES).map((k) => caches.delete(k)));
  await self.clients.claim();
})()));
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (isTile(url)) { // cache-first, persistent
    e.respondWith((async () => {
      const c = await caches.open(TILES);
      const hit = await c.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res && res.ok) { c.put(req, res.clone()); trim(); }
      return res;
    })());
    return;
  }
  if (url.origin !== self.location.origin) return; // leave the OGN API to the network
  e.respondWith((async () => { // network-first for the app shell
    try {
      const res = await fetch(req);
      if (res && res.ok) { const c = await caches.open(CACHE); c.put(req, res.clone()); }
      return res;
    } catch (err) {
      const cached = await caches.match(req);
      if (cached) return cached;
      throw err;
    }
  })());
});
`;
await writeFile(`${root}dist/sw.js`, sw);

// Wire the manifest + theme/icon links into the built HTML (stable names, so
// Bun never rewrites or hashes them).
const htmlPath = `${root}dist/index.html`;
let html = await readFile(htmlPath, 'utf8');
html = html.replace('</head>',
  `<link rel="manifest" href="manifest.json">` +
  `<meta name="theme-color" content="${themeColor}">` +
  `<link rel="apple-touch-icon" href="icon-192.png">` +
  // iOS/Android home-screen: run fullscreen (standalone) with a matching title
  // and status bar, since Safari ignores the manifest's display on older versions.
  `<meta name="mobile-web-app-capable" content="yes">` +
  `<meta name="apple-mobile-web-app-capable" content="yes">` +
  `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">` +
  `<meta name="apple-mobile-web-app-title" content="OGN 3D"></head>`);
await writeFile(htmlPath, html);

console.log(`built ogn-3d-viewer ${version} (${hash}) + PWA (manifest, icons, sw.js)`);
